baseURL            = "https://casadogaspar.pages.dev/"
locale             = "en"
defaultContentLanguage = "en"
title              = "Casa do Gaspar"

[params]
description = "Tech, life and everything in between"
author      = "Gaspar"
dateFormat  = "2006-01-02"
avatarURL   = "/images/avatar.png"

[params.social]
github  = "gaspar-d"
youtube = "https://www.youtube.com/@casadogaspar"

[menu]
[[menu.main]]
identifier = "posts"
name       = "Posts"
url        = "/posts/"
weight     = 1
[[menu.main]]
identifier = "tags"
name       = "Tags"
url        = "/tags/"
weight     = 2
[[menu.main]]
identifier = "categories"
name       = "Categories"
url        = "/categories/"
weight     = 3

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark.extensions.extras.mark]
enable = true

[taxonomies]
tag      = "tags"
category = "categories"

[outputs]
home = ["HTML", "RSS"]
